import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
  name: "AnimatedDrawings",
  projects: [
    App.path
  ],
  schemes: [],
  additionalFiles: [
    "README.md"
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: true,
    autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .all)
  )
)
